---

- hosts: web

  become: yes
  become_user: root

  roles:
    - docker-role

  tasks:
    - name: docker network
      docker_network:
        name: foobar

    - name: nginx container
      docker_container:
        image: nginx
        name: nginx
        state: started
        ports:
          - 0.0.0.0:80:80
      tags:
        - deploy
